//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraceWizard.TwApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public string GraphBackgroundColor {
            get {
                return ((string)(this["GraphBackgroundColor"]));
            }
            set {
                this["GraphBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGray")]
        public string GraphVerticalGuidelineColor {
            get {
                return ((string)(this["GraphVerticalGuidelineColor"]));
            }
            set {
                this["GraphVerticalGuidelineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public string GraphRulerColor {
            get {
                return ((string)(this["GraphRulerColor"]));
            }
            set {
                this["GraphRulerColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowDetailedEventToolTips {
            get {
                return ((bool)(this["ShowDetailedEventToolTips"]));
            }
            set {
                this["ShowDetailedEventToolTips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableSpeechRecognition {
            get {
                return ((bool)(this["EnableSpeechRecognition"]));
            }
            set {
                this["EnableSpeechRecognition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J48 Classifier")]
        public string Classifier {
            get {
                return ((string)(this["Classifier"]));
            }
            set {
                this["Classifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MinutesBetweenBackgroundSaves {
            get {
                return ((int)(this["MinutesBetweenBackgroundSaves"]));
            }
            set {
                this["MinutesBetweenBackgroundSaves"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int MinutesToStartFirstCycle {
            get {
                return ((int)(this["MinutesToStartFirstCycle"]));
            }
            set {
                this["MinutesToStartFirstCycle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DirectoryLog {
            get {
                return ((string)(this["DirectoryLog"]));
            }
            set {
                this["DirectoryLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DirectoryAnalysis {
            get {
                return ((string)(this["DirectoryAnalysis"]));
            }
            set {
                this["DirectoryAnalysis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowStatusBar {
            get {
                return ((bool)(this["ShowStatusBar"]));
            }
            set {
                this["ShowStatusBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowUnusedFixtures {
            get {
                return ((bool)(this["ShowUnusedFixtures"]));
            }
            set {
                this["ShowUnusedFixtures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowSimilarCountInEventToolTips {
            get {
                return ((bool)(this["ShowSimilarCountInEventToolTips"]));
            }
            set {
                this["ShowSimilarCountInEventToolTips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maximized")]
        public global::System.Windows.WindowState WindowState {
            get {
                return ((global::System.Windows.WindowState)(this["WindowState"]));
            }
            set {
                this["WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowDiagnosticEventToolTips {
            get {
                return ((bool)(this["ShowDiagnosticEventToolTips"]));
            }
            set {
                this["ShowDiagnosticEventToolTips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowVerticalGuideline {
            get {
                return ((bool)(this["ShowVerticalGuideline"]));
            }
            set {
                this["ShowVerticalGuideline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowViewTimeFrame {
            get {
                return ((bool)(this["ShowViewTimeFrame"]));
            }
            set {
                this["ShowViewTimeFrame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTraceTimeFrame {
            get {
                return ((bool)(this["ShowTraceTimeFrame"]));
            }
            set {
                this["ShowTraceTimeFrame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTimeFrameAboveGraph {
            get {
                return ((bool)(this["ShowTimeFrameAboveGraph"]));
            }
            set {
                this["ShowTimeFrameAboveGraph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string GraphHorizontalGuidelineColor {
            get {
                return ((string)(this["GraphHorizontalGuidelineColor"]));
            }
            set {
                this["GraphHorizontalGuidelineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string SelectionTickColor {
            get {
                return ((string)(this["SelectionTickColor"]));
            }
            set {
                this["SelectionTickColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHorizontalGuideline {
            get {
                return ((bool)(this["ShowHorizontalGuideline"]));
            }
            set {
                this["ShowHorizontalGuideline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowSelectionRulerByDefault {
            get {
                return ((bool)(this["ShowSelectionRulerByDefault"]));
            }
            set {
                this["ShowSelectionRulerByDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowSelectionRulerAboveGraph {
            get {
                return ((bool)(this["ShowSelectionRulerAboveGraph"]));
            }
            set {
                this["ShowSelectionRulerAboveGraph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowSelectedEventPanel {
            get {
                return ((bool)(this["ShowSelectedEventPanel"]));
            }
            set {
                this["ShowSelectedEventPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowSummaryPanel {
            get {
                return ((bool)(this["ShowSummaryPanel"]));
            }
            set {
                this["ShowSummaryPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowLogPanel {
            get {
                return ((bool)(this["ShowLogPanel"]));
            }
            set {
                this["ShowLogPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowReportsPanel {
            get {
                return ((bool)(this["ShowReportsPanel"]));
            }
            set {
                this["ShowReportsPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCommandPanel {
            get {
                return ((bool)(this["ShowCommandPanel"]));
            }
            set {
                this["ShowCommandPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowGraphToolBar {
            get {
                return ((bool)(this["ShowGraphToolBar"]));
            }
            set {
                this["ShowGraphToolBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowPieChartsPanel {
            get {
                return ((bool)(this["ShowPieChartsPanel"]));
            }
            set {
                this["ShowPieChartsPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string AnalysisPanelBackgroundColor {
            get {
                return ((string)(this["AnalysisPanelBackgroundColor"]));
            }
            set {
                this["AnalysisPanelBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowGraphToolBarAboveGraph {
            get {
                return ((bool)(this["ShowGraphToolBarAboveGraph"]));
            }
            set {
                this["ShowGraphToolBarAboveGraph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2 hours")]
        public string ViewportSeconds {
            get {
                return ((string)(this["ViewportSeconds"]));
            }
            set {
                this["ViewportSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowEventToolTips {
            get {
                return ((bool)(this["ShowEventToolTips"]));
            }
            set {
                this["ShowEventToolTips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowFixturesInGraphToolBar {
            get {
                return ((bool)(this["ShowFixturesInGraphToolBar"]));
            }
            set {
                this["ShowFixturesInGraphToolBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SingleLineGraphToolBar {
            get {
                return ((bool)(this["SingleLineGraphToolBar"]));
            }
            set {
                this["SingleLineGraphToolBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowFixturesRulerByDefault {
            get {
                return ((bool)(this["ShowFixturesRulerByDefault"]));
            }
            set {
                this["ShowFixturesRulerByDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowFixturesRulerAboveGraph {
            get {
                return ((bool)(this["ShowFixturesRulerAboveGraph"]));
            }
            set {
                this["ShowFixturesRulerAboveGraph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelectFirstEvent {
            get {
                return ((bool)(this["SelectFirstEvent"]));
            }
            set {
                this["SelectFirstEvent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Any")]
        public string FindMode {
            get {
                return ((string)(this["FindMode"]));
            }
            set {
                this["FindMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Without Adoption")]
        public string ManualClassificationMode {
            get {
                return ((string)(this["ManualClassificationMode"]));
            }
            set {
                this["ManualClassificationMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CycleCommandActions {
            get {
                return ((bool)(this["CycleCommandActions"]));
            }
            set {
                this["CycleCommandActions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCurrentEventPanel {
            get {
                return ((bool)(this["ShowCurrentEventPanel"]));
            }
            set {
                this["ShowCurrentEventPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowEventPanelsOnLeft {
            get {
                return ((bool)(this["ShowEventPanelsOnLeft"]));
            }
            set {
                this["ShowEventPanelsOnLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowClassificationRulerAboveGraph {
            get {
                return ((bool)(this["ShowClassificationRulerAboveGraph"]));
            }
            set {
                this["ShowClassificationRulerAboveGraph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowApprovalRulerAboveGraph {
            get {
                return ((bool)(this["ShowApprovalRulerAboveGraph"]));
            }
            set {
                this["ShowApprovalRulerAboveGraph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowApprovalRulerByDefault {
            get {
                return ((bool)(this["ShowApprovalRulerByDefault"]));
            }
            set {
                this["ShowApprovalRulerByDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowClassificationRulerByDefault {
            get {
                return ((bool)(this["ShowClassificationRulerByDefault"]));
            }
            set {
                this["ShowClassificationRulerByDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowClassifyFirstCyclesUsingMachineLearningButton {
            get {
                return ((bool)(this["ShowClassifyFirstCyclesUsingMachineLearningButton"]));
            }
            set {
                this["ShowClassifyFirstCyclesUsingMachineLearningButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Selected")]
        public string ClassificationActionMode {
            get {
                return ((string)(this["ClassificationActionMode"]));
            }
            set {
                this["ClassificationActionMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string UpgradeRequired {
            get {
                return ((string)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
    }
}
